# Generated by Django 5.2.8 on 2026-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
